### ISSUE TITLE
can we use it in php laravel?

### ISSUE THREAD

**Issue by iSarahSajjad** [leon-vv/node-image-scraper#5]
I wonder it's only work in node can I use it in php laravel and moreover before saving the image can i show all images of the url?

**Comment by leon-vv** [comment]
I do not understand your question exactly. However as far as I know it's not trivial to call a Node.js function directly from PHP. You could invoke this program in a separate process of course.

**Comment by iSarahSajjad** [comment]
can ve use it on react.js actually im new in react, and i want image scrapping functionality in react, can we use your library in react.js

**Comment by leon-vv** [comment]
Sure, go ahead.
