### ISSUE TITLE
image.saveTo();  is not a function

### ISSUE THREAD

**Issue by jackbashed** [leon-vv/node-image-scraper#7]
That's what it says every time I try to use image.saveTo(); I'm probably using it wrong so is it possible you could link an example of code using image.saveTo

**Comment by leon-vv** [comment]
There is an example at the bottom of the readme.md file

**Comment by jackbashed** [comment]
There is an example of using image.save(); however, there is no example of using image.saveTo. I'm trying to get the images saved to a folder. @leon-vv

**Comment by leon-vv** [comment]
Sorry I was too quick with my answer.

```javascript
var Scraper = require('image-scraper');
var scraper = new Scraper('https://apod.nasa.gov/apod/astropix.html');

scraper.scrape(function(image) { 
        image.saveTo = '~/Pictures/SaveHere';
	image.save();
});
```

This should work.

**Comment by jackbashed** [comment]
No problem, thanks for the quick responses! I'll try this out.

**Comment by jackbashed** [comment]
Awesome, I got it, thanks!

**Comment by leon-vv** [comment]
Happy to help.
